--
-- SQLiteStudio v3.4.4 生成的文件，周五 6月 7 15:52:14 2024
--
-- 所用的文本编码：System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- 表：VSysMenu
CREATE TABLE IF NOT EXISTS VSysMenu (-- 主键Id
    Id          INTEGER NOT NULL
                        CONSTRAINT PK_VSysMenu PRIMARY KEY AUTOINCREMENT,-- 记录创建时间
    CreateTime  TEXT    NOT NULL,-- 记录上次修改时间
    ModifyTime  TEXT    NOT NULL,-- 是否被[软]删除
    IsDel       INTEGER NOT NULL,-- 并发标识
    RowVersion  TEXT    NOT NULL
                        DEFAULT (CURRENT_TIMESTAMP),-- 图标
    Icon        TEXT    NOT NULL,-- 路由名称
    RouteName   TEXT    NOT NULL,-- 路由地址
    RoutePath   TEXT    NOT NULL,-- 组件路径
    Component   TEXT    NOT NULL,-- 路由重定向
    Redirect    TEXT,
    RequireAuth/* 是否要求授权验证 */ INTEGER NOT NULL,
    IsKeepalive/* 是否缓存 */ INTEGER NOT NULL,
    Data/* 附带数据 */        TEXT    NOT NULL,
    Name/* 名称 */        TEXT    NOT NULL,
    ParentId/* 父级Id */    INTEGER NOT NULL,
    FamilyTree/* 成员层级树 */  TEXT    NOT NULL,
    Level/* 层级 */       INTEGER NOT NULL,
    IsShow/* 是否显示 */      INTEGER NOT NULL,
    SortId/* 排序值 */      INTEGER NOT NULL
);

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         1,
                         '2022-11-08 01:31:49',
                         '2022-11-14 01:14:39.571892',
                         0,
                         '2022-11-07 17:31:49',
                         'ri:settings-2-fill',
                         'system',
                         '/system',
                         'LAYOUT',
                         '/system/users',
                         1,
                         0,
                         '{}',
                         '系统设置',
                         0,
                         '',
                         1,
                         1,
                         200
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         2,
                         '2022-11-08 01:33:15',
                         '2022-11-14 01:15:10.61298',
                         0,
                         '2022-11-07 17:33:15',
                         'ri:user-2-fill',
                         'users',
                         '/system/users',
                         'system/users/index.vue',
                         NULL,
                         1,
                         1,
                         '{}',
                         '系统用户管理',
                         1,
                         '1',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         3,
                         '2022-11-08 01:35:37',
                         '2022-11-14 01:20:27.152034',
                         0,
                         '2022-11-07 17:35:37',
                         'ri:layout-left-2-fill',
                         'menus',
                         '/system/menus',
                         'system/menus/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '系统菜单管理',
                         1,
                         '1',
                         2,
                         1,
                         1
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         4,
                         '2022-11-08 01:36:14',
                         '2022-11-14 01:16:35.85185',
                         0,
                         '2022-11-07 17:36:14',
                         'ri:file-user-fill',
                         'roles',
                         '/system/roles',
                         'system/roles/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '系统角色管理',
                         1,
                         '1',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         5,
                         '2022-11-08 01:36:35',
                         '2022-11-16 14:41:02.447292',
                         0,
                         '2022-11-07 17:36:35',
                         'ri:user-settings-fill',
                         'user-role',
                         '/system/user-role',
                         'system/user-role/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '用户角色管理',
                         1,
                         '1',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         6,
                         '2022-11-08 01:38:28',
                         '2022-11-14 01:15:41.554446',
                         0,
                         '2022-11-07 17:38:28',
                         'ri:google-play-fill',
                         'permission',
                         '/permission',
                         'LAYOUT',
                         '/permission/user-auth',
                         1,
                         0,
                         '{}',
                         '权限管理',
                         0,
                         '',
                         1,
                         1,
                         100
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         7,
                         '2022-11-08 01:39:31',
                         '2022-11-16 14:41:11.976568',
                         0,
                         '2022-11-07 17:39:31',
                         'ri:shield-user-line',
                         'user-auth',
                         '/permission/user-auth',
                         'permission/user-auth/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '用户权限管理',
                         6,
                         '6',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         8,
                         '2022-11-08 01:40:01',
                         '2022-11-14 01:16:23.831227',
                         0,
                         '2022-11-07 17:40:01',
                         'ri:shield-user-line',
                         'role-auth',
                         '/permission/role-auth',
                         'permission/role-auth/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '角色权限管理',
                         6,
                         '6',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         9,
                         '2022-11-08 01:42:27',
                         '2022-11-21 18:00:25.203427',
                         0,
                         '2022-11-07 17:42:27',
                         'ri:star-fill',
                         'demo',
                         '/demos',
                         'LAYOUT',
                         '/demos/kindeditor',
                         1,
                         0,
                         '{}',
                         '组件演示',
                         0,
                         '',
                         1,
                         1,
                         500
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         10,
                         '2022-11-08 01:43:37',
                         '2024-06-05 17:11:49.6764857',
                         0,
                         '2022-11-07 17:43:37',
                         'ri:edit-2-fill',
                         'kindeditor',
                         '/demos/kindeditor',
                         'demos/editors/kindeditor.vue',
                         '',
                         1,
                         1,
                         '{}',
                         'KindEditor',
                         9,
                         '9',
                         2,
                         1,
                         5
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         11,
                         '2022-11-08 01:47:00',
                         '2023-12-08 21:15:45.138366',
                         0,
                         '2022-11-07 17:47:00',
                         'ri:dashboard-2-fill',
                         'dashboard',
                         '/dashboard/index',
                         'dashboard/index.vue',
                         '',
                         1,
                         0,
                         '{}',
                         '仪表盘',
                         0,
                         '',
                         1,
                         1,
                         99998
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         13,
                         '2022-11-13 21:34:36',
                         '2022-11-16 02:52:43.848809',
                         0,
                         '2022-11-13 13:34:36',
                         'ri:upload-cloud-2-fill',
                         'uploader',
                         '/demos/uploader',
                         'demos/uploaders/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '图片上传',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         14,
                         '2022-11-13 21:57:20',
                         '2022-11-16 16:17:42.927554',
                         0,
                         '2022-11-13 13:57:20',
                         'ri:remixicon-line',
                         'iconPicker',
                         '/demos/icon-picker',
                         'demos/pickers/icon.vue',
                         '',
                         1,
                         0,
                         '{}',
                         '图标选择器',
                         9,
                         '9',
                         2,
                         1,
                         10
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         15,
                         '2022-11-16 16:17:25.054039',
                         '2022-11-16 16:17:25.0541',
                         0,
                         '2022-11-16 08:17:25',
                         'ri:file-user-fill',
                         'avatar-cropper',
                         '/demos/uploaders/avatar',
                         'demos/uploaders/avatar.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '头像裁剪',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         16,
                         '2022-11-16 17:36:45',
                         '2022-11-29 14:00:49.14154',
                         0,
                         '2022-11-16 09:36:45',
                         'ri:book-read-fill',
                         'dictionary',
                         '/dictionary',
                         'dictionary/index.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '字典配置',
                         0,
                         '',
                         1,
                         1,
                         300
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         17,
                         '2022-11-17 13:48:13',
                         '2022-11-17 13:51:20.051209',
                         0,
                         '2022-11-17 05:48:13',
                         'ri:file-copy-fill',
                         'copy',
                         '/directives/copy',
                         'demos/directives/copy.vue',
                         '',
                         1,
                         0,
                         '{}',
                         '文本复制',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         18,
                         '2022-11-21 18:16:48',
                         '2022-11-21 22:33:21.494547',
                         0,
                         '2022-11-21 10:16:48',
                         'ri:qr-code-line',
                         'qrcode',
                         '/demos/qrcode',
                         'demos/qrcode.vue',
                         '',
                         1,
                         0,
                         '{}',
                         '二维码生成',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         19,
                         '2022-11-21 22:53:13',
                         '2022-11-21 23:20:21.150412',
                         0,
                         '2022-11-21 14:53:13',
                         'ri:map-2-fill',
                         'area-picker',
                         '/demos/area-picker',
                         'demos/pickers/area.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '地区选择',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         20,
                         '2022-11-21 23:38:54.428938',
                         '2022-11-21 23:38:54.428944',
                         0,
                         '2022-11-21 15:38:54',
                         'ri:price-tag-3-fill',
                         'tag-input',
                         '/demos/tag-input',
                         'demos/taginput.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '标签输入',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         22,
                         '2022-11-24 02:19:05.035201',
                         '2022-11-24 02:19:05.035206',
                         0,
                         '2022-11-23 18:19:05',
                         'ri:health-book-fill',
                         'props',
                         '/testers/props',
                         'testers/props.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '字典测试',
                         21,
                         '21',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         23,
                         '2022-11-24 17:05:12',
                         '2022-11-25 00:46:58.480588',
                         0,
                         '2022-11-24 09:05:12',
                         'ri:chat-follow-up-fill',
                         'count-up',
                         '/demos/count-up',
                         'demos/countup.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '数字自增',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         25,
                         '2022-11-27 00:23:56',
                         '2022-12-23 15:49:04.410695',
                         0,
                         '2022-11-26 16:23:56',
                         'ri:external-link-fill',
                         'outlink',
                         'https://www.baidu.com',
                         '',
                         '',
                         1,
                         1,
                         '{}',
                         '测试外链',
                         28,
                         '28',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         26,
                         '2022-11-27 01:09:36',
                         '2022-11-29 10:35:57.594462',
                         0,
                         '2022-11-26 17:09:36',
                         'ri:window-line',
                         'iframe1',
                         '/frame/baidu',
                         'IFRAME',
                         'https://element-plus.org/zh-CN',
                         1,
                         1,
                         '{}',
                         '测试iframe',
                         28,
                         '28',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         27,
                         '2022-11-27 01:49:26',
                         '2022-11-29 10:47:14.776594',
                         0,
                         '2022-11-26 17:49:26',
                         'ri:terminal-window-fill',
                         'iframe2',
                         '/to-frame-test',
                         'IFRAME',
                         'http://h5.ddhudong.com/',
                         1,
                         0,
                         '{}',
                         '测试iframe2',
                         28,
                         '28',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         28,
                         '2022-11-29 10:35:20.150898',
                         '2022-11-29 10:35:20.150958',
                         0,
                         '2022-11-29 02:35:20',
                         'ri:computer-line',
                         '',
                         '',
                         'LAYOUT',
                         '',
                         1,
                         1,
                         '{}',
                         '外部页面',
                         0,
                         '',
                         1,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         29,
                         '2022-11-29 10:51:20.731228',
                         '2022-11-29 10:51:20.731286',
                         0,
                         '2022-11-29 02:51:20',
                         'ri:error-warning-fill',
                         'iframe-error',
                         '/iframe/error',
                         'IFRAME',
                         '',
                         1,
                         1,
                         '{}',
                         '错误演示',
                         28,
                         '28',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         30,
                         '2022-11-29 11:31:05.217482',
                         '2022-11-29 11:31:05.217526',
                         0,
                         '2022-11-29 03:31:05',
                         'ri:link-unlink-m',
                         'iframe-404',
                         '/iframe/404',
                         'IFRAME',
                         'http://u.iddhd.com',
                         1,
                         1,
                         '{}',
                         '错误的链接',
                         28,
                         '28',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         32,
                         '2022-12-12 11:17:11.148006',
                         '2022-12-12 11:17:11.148087',
                         0,
                         '2022-12-12 03:17:11',
                         'ri:water-flash-fill',
                         'water-marker',
                         '/demos/directives/water-marker',
                         'demos/directives/water-marker.vue',
                         '',
                         1,
                         1,
                         '{}',
                         '水印',
                         9,
                         '9',
                         2,
                         1,
                         0
                     );

INSERT INTO VSysMenu (
                         Id,
                         CreateTime,
                         ModifyTime,
                         IsDel,
                         RowVersion,
                         Icon,
                         RouteName,
                         RoutePath,
                         Component,
                         Redirect,
                         RequireAuth,
                         IsKeepalive,
                         Data,
                         Name,
                         ParentId,
                         FamilyTree,
                         Level,
                         IsShow,
                         SortId
                     )
                     VALUES (
                         33,
                         '2023-07-04 10:05:06',
                         '2023-07-04 10:32:44.030976',
                         0,
                         '2023-07-04 02:05:06',
                         'ri:markdown-fill',
                         'markdown',
                         '/demos/markdown',
                         'demos/editors/markdown.vue',
                         '',
                         1,
                         0,
                         '{}',
                         'Markdown',
                         9,
                         '9',
                         2,
                         1,
                         4
                     );


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
